//! Complete character encoding tables for all supported encodings
//!
//! This module contains the complete 256-element character tables for each supported
//! encoding, mapping byte values to Unicode code points.

use super::Encoding;

/// Get the character table for a specific encoding
pub fn get_encoding_chars(encoding: Encoding) -> &'static [Option<char>; 256] {
    return match encoding {
        // Unicode and ASCII
        Encoding::UTF8 | Encoding::ASCII => &ASCII_CHARS,

        // ISO-8859 series
        Encoding::ISO_8859_1 => &ISO_8859_1_CHARS,
        Encoding::ISO_8859_15 => &ISO_8859_15_CHARS, // Latin-9 with Euro

        // Windows code pages
        Encoding::WINDOWS_1252 => &WINDOWS_1252_CHARS,
        Encoding::WINDOWS_1250 => &WINDOWS_1250_CHARS,

        // DOS code pages
        Encoding::CP_437 => &CP_437_CHARS,
        Encoding::CP_850 => &CP_850_CHARS,

        // EBCDIC variants
        Encoding::EBCDIC_037 => &EBCDIC_037_CHARS,
        Encoding::EBCDIC_500 => &EBCDIC_500_CHARS,
        Encoding::EBCDIC_1047 => &EBCDIC_1047_CHARS,

        // Asian encodings (scaffolded, TODO: fill in real tables)
        Encoding::SHIFT_JIS => &SHIFT_JIS_CHARS,
        Encoding::EUC_JP => &EUC_JP_CHARS,
        Encoding::GB2312 => &GB2312_CHARS,
        Encoding::BIG5 => &BIG5_CHARS,
        Encoding::EUC_KR => &EUC_KR_CHARS,

        // For unsupported encodings, fall back to ASCII for now
        _ => &ASCII_CHARS,
    };
}

/// Shift_JIS (Japanese) character table (scaffold)
/// TODO: Fill in with real Shift_JIS byte-to-Unicode mappings
pub static SHIFT_JIS_CHARS: [Option<char>; 256] = [None; 256];

/// EUC-JP (Japanese) character table (scaffold)
/// TODO: Fill in with real EUC-JP byte-to-Unicode mappings
pub static EUC_JP_CHARS: [Option<char>; 256] = [None; 256];

/// GB2312 (Simplified Chinese) character table (scaffold)
/// TODO: Fill in with real GB2312 byte-to-Unicode mappings
pub static GB2312_CHARS: [Option<char>; 256] = [None; 256];

/// Big5 (Traditional Chinese) character table (scaffold)
/// TODO: Fill in with real Big5 byte-to-Unicode mappings
pub static BIG5_CHARS: [Option<char>; 256] = [None; 256];

/// EUC-KR (Korean) character table (scaffold)
/// TODO: Fill in with real EUC-KR byte-to-Unicode mappings
pub static EUC_KR_CHARS: [Option<char>; 256] = [None; 256];

/// ASCII character table (7-bit, 0-127 mapped, rest None)
pub static ASCII_CHARS: [Option<char>; 256] = {
    let mut chars = [None; 256];
    let mut i = 0;
    while i <= 127 {
        chars[i] = Some(i as u8 as char);
        i += 1;
    }
    chars
};

/// ISO-8859-1 (Latin-1) character table - complete 1:1 mapping to Unicode
pub static ISO_8859_1_CHARS: [Option<char>; 256] = {
    let mut chars = [None; 256];
    let mut i = 0;
    while i < 256 {
        chars[i] = Some(i as u8 as char);
        i += 1;
    }
    chars
};

/// Windows-1252 character table with proper C1 control mappings
pub static WINDOWS_1252_CHARS: [Option<char>; 256] = [
    // 0x00-0x1F: C0 controls (same as ASCII)
    Some('\u{0000}'),
    Some('\u{0001}'),
    Some('\u{0002}'),
    Some('\u{0003}'),
    Some('\u{0004}'),
    Some('\u{0005}'),
    Some('\u{0006}'),
    Some('\u{0007}'),
    Some('\u{0008}'),
    Some('\u{0009}'),
    Some('\u{000A}'),
    Some('\u{000B}'),
    Some('\u{000C}'),
    Some('\u{000D}'),
    Some('\u{000E}'),
    Some('\u{000F}'),
    Some('\u{0010}'),
    Some('\u{0011}'),
    Some('\u{0012}'),
    Some('\u{0013}'),
    Some('\u{0014}'),
    Some('\u{0015}'),
    Some('\u{0016}'),
    Some('\u{0017}'),
    Some('\u{0018}'),
    Some('\u{0019}'),
    Some('\u{001A}'),
    Some('\u{001B}'),
    Some('\u{001C}'),
    Some('\u{001D}'),
    Some('\u{001E}'),
    Some('\u{001F}'),
    // 0x20-0x7F: ASCII printable (same as ISO-8859-1)
    Some(' '),
    Some('!'),
    Some('"'),
    Some('#'),
    Some('$'),
    Some('%'),
    Some('&'),
    Some('\''),
    Some('('),
    Some(')'),
    Some('*'),
    Some('+'),
    Some(','),
    Some('-'),
    Some('.'),
    Some('/'),
    Some('0'),
    Some('1'),
    Some('2'),
    Some('3'),
    Some('4'),
    Some('5'),
    Some('6'),
    Some('7'),
    Some('8'),
    Some('9'),
    Some(':'),
    Some(';'),
    Some('<'),
    Some('='),
    Some('>'),
    Some('?'),
    Some('@'),
    Some('A'),
    Some('B'),
    Some('C'),
    Some('D'),
    Some('E'),
    Some('F'),
    Some('G'),
    Some('H'),
    Some('I'),
    Some('J'),
    Some('K'),
    Some('L'),
    Some('M'),
    Some('N'),
    Some('O'),
    Some('P'),
    Some('Q'),
    Some('R'),
    Some('S'),
    Some('T'),
    Some('U'),
    Some('V'),
    Some('W'),
    Some('X'),
    Some('Y'),
    Some('Z'),
    Some('['),
    Some('\\'),
    Some(']'),
    Some('^'),
    Some('_'),
    Some('`'),
    Some('a'),
    Some('b'),
    Some('c'),
    Some('d'),
    Some('e'),
    Some('f'),
    Some('g'),
    Some('h'),
    Some('i'),
    Some('j'),
    Some('k'),
    Some('l'),
    Some('m'),
    Some('n'),
    Some('o'),
    Some('p'),
    Some('q'),
    Some('r'),
    Some('s'),
    Some('t'),
    Some('u'),
    Some('v'),
    Some('w'),
    Some('x'),
    Some('y'),
    Some('z'),
    Some('{'),
    Some('|'),
    Some('}'),
    Some('~'),
    Some('\u{007F}'),
    // 0x80-0x9F: Windows-1252 specific mappings (differ from ISO-8859-1)
    Some('\u{20AC}'),
    None,
    Some('\u{201A}'),
    Some('\u{0192}'), // Euro, unused, single low-9 quotation mark, florin
    Some('\u{201E}'),
    Some('\u{2026}'),
    Some('\u{2020}'),
    Some('\u{2021}'), // double low-9 quotation mark, ellipsis, dagger, double dagger
    Some('\u{02C6}'),
    Some('\u{2030}'),
    Some('\u{0160}'),
    Some('\u{2039}'), // circumflex, per mille, S caron, single left angle quotation
    Some('\u{0152}'),
    None,
    Some('\u{017D}'),
    None, // OE ligature, unused, Z caron, unused
    None,
    Some('\u{2018}'),
    Some('\u{2019}'),
    Some('\u{201C}'), // unused, left single quotation, right single quotation, left double quotation
    Some('\u{201D}'),
    Some('\u{2022}'),
    Some('\u{2013}'),
    Some('\u{2014}'), // right double quotation, bullet, en dash, em dash
    Some('\u{02DC}'),
    Some('\u{2122}'),
    Some('\u{0161}'),
    Some('\u{203A}'), // tilde, trademark, s caron, single right angle quotation
    Some('\u{0153}'),
    None,
    Some('\u{017E}'),
    Some('\u{0178}'), // oe ligature, unused, z caron, Y diaeresis
    // 0xA0-0xFF: Same as ISO-8859-1
    Some('\u{00A0}'),
    Some('\u{00A1}'),
    Some('\u{00A2}'),
    Some('\u{00A3}'),
    Some('\u{00A4}'),
    Some('\u{00A5}'),
    Some('\u{00A6}'),
    Some('\u{00A7}'),
    Some('\u{00A8}'),
    Some('\u{00A9}'),
    Some('\u{00AA}'),
    Some('\u{00AB}'),
    Some('\u{00AC}'),
    Some('\u{00AD}'),
    Some('\u{00AE}'),
    Some('\u{00AF}'),
    Some('\u{00B0}'),
    Some('\u{00B1}'),
    Some('\u{00B2}'),
    Some('\u{00B3}'),
    Some('\u{00B4}'),
    Some('\u{00B5}'),
    Some('\u{00B6}'),
    Some('\u{00B7}'),
    Some('\u{00B8}'),
    Some('\u{00B9}'),
    Some('\u{00BA}'),
    Some('\u{00BB}'),
    Some('\u{00BC}'),
    Some('\u{00BD}'),
    Some('\u{00BE}'),
    Some('\u{00BF}'),
    Some('\u{00C0}'),
    Some('\u{00C1}'),
    Some('\u{00C2}'),
    Some('\u{00C3}'),
    Some('\u{00C4}'),
    Some('\u{00C5}'),
    Some('\u{00C6}'),
    Some('\u{00C7}'),
    Some('\u{00C8}'),
    Some('\u{00C9}'),
    Some('\u{00CA}'),
    Some('\u{00CB}'),
    Some('\u{00CC}'),
    Some('\u{00CD}'),
    Some('\u{00CE}'),
    Some('\u{00CF}'),
    Some('\u{00D0}'),
    Some('\u{00D1}'),
    Some('\u{00D2}'),
    Some('\u{00D3}'),
    Some('\u{00D4}'),
    Some('\u{00D5}'),
    Some('\u{00D6}'),
    Some('\u{00D7}'),
    Some('\u{00D8}'),
    Some('\u{00D9}'),
    Some('\u{00DA}'),
    Some('\u{00DB}'),
    Some('\u{00DC}'),
    Some('\u{00DD}'),
    Some('\u{00DE}'),
    Some('\u{00DF}'),
    Some('\u{00E0}'),
    Some('\u{00E1}'),
    Some('\u{00E2}'),
    Some('\u{00E3}'),
    Some('\u{00E4}'),
    Some('\u{00E5}'),
    Some('\u{00E6}'),
    Some('\u{00E7}'),
    Some('\u{00E8}'),
    Some('\u{00E9}'),
    Some('\u{00EA}'),
    Some('\u{00EB}'),
    Some('\u{00EC}'),
    Some('\u{00ED}'),
    Some('\u{00EE}'),
    Some('\u{00EF}'),
    Some('\u{00F0}'),
    Some('\u{00F1}'),
    Some('\u{00F2}'),
    Some('\u{00F3}'),
    Some('\u{00F4}'),
    Some('\u{00F5}'),
    Some('\u{00F6}'),
    Some('\u{00F7}'),
    Some('\u{00F8}'),
    Some('\u{00F9}'),
    Some('\u{00FA}'),
    Some('\u{00FB}'),
    Some('\u{00FC}'),
    Some('\u{00FD}'),
    Some('\u{00FE}'),
    Some('\u{00FF}'),
];

/// IBM EBCDIC Code Page 037 (US/Canada) - Complete character table
pub static EBCDIC_037_CHARS: [Option<char>; 256] = [
    // 0x00-0x0F
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0x10-0x1F
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0x20-0x2F
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0x30-0x3F
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0x40-0x4F: Space and punctuation
    Some(' '),
    Some('\u{00A0}'),
    Some('\u{00E2}'),
    Some('\u{00E4}'),
    Some('\u{00E0}'),
    Some('\u{00E1}'),
    Some('\u{00E3}'),
    Some('\u{00E5}'),
    Some('\u{00E7}'),
    Some('\u{00F1}'),
    Some('\u{00A2}'),
    Some('.'),
    Some('<'),
    Some('('),
    Some('+'),
    Some('|'),
    // 0x50-0x5F: Punctuation and symbols
    Some('&'),
    Some('\u{00E9}'),
    Some('\u{00EA}'),
    Some('\u{00EB}'),
    Some('\u{00E8}'),
    Some('\u{00ED}'),
    Some('\u{00EE}'),
    Some('\u{00EF}'),
    Some('\u{00EC}'),
    Some('\u{00DF}'),
    Some('!'),
    Some('$'),
    Some('*'),
    Some(')'),
    Some(';'),
    Some('\u{00AC}'),
    // 0x60-0x6F: More punctuation
    Some('-'),
    Some('/'),
    Some('\u{00C2}'),
    Some('\u{00C4}'),
    Some('\u{00C0}'),
    Some('\u{00C1}'),
    Some('\u{00C3}'),
    Some('\u{00C5}'),
    Some('\u{00C7}'),
    Some('\u{00D1}'),
    Some('\u{00A6}'),
    Some(','),
    Some('%'),
    Some('_'),
    Some('>'),
    Some('?'),
    // 0x70-0x7F: More symbols
    Some('\u{00F8}'),
    Some('\u{00C9}'),
    Some('\u{00CA}'),
    Some('\u{00CB}'),
    Some('\u{00C8}'),
    Some('\u{00CD}'),
    Some('\u{00CE}'),
    Some('\u{00CF}'),
    Some('\u{00CC}'),
    Some('`'),
    Some(':'),
    Some('#'),
    Some('@'),
    Some('\''),
    Some('='),
    Some('"'),
    // 0x80-0x8F: More symbols and lowercase letters
    Some('\u{00D8}'),
    Some('a'),
    Some('b'),
    Some('c'),
    Some('d'),
    Some('e'),
    Some('f'),
    Some('g'),
    Some('h'),
    Some('i'),
    Some('\u{00AB}'),
    Some('\u{00BB}'),
    Some('\u{00F0}'),
    Some('\u{00FD}'),
    Some('\u{00FE}'),
    Some('\u{00B1}'),
    // 0x90-0x9F: More lowercase letters
    Some('\u{00B0}'),
    Some('j'),
    Some('k'),
    Some('l'),
    Some('m'),
    Some('n'),
    Some('o'),
    Some('p'),
    Some('q'),
    Some('r'),
    Some('\u{00AA}'),
    Some('\u{00BA}'),
    Some('\u{00E6}'),
    Some('\u{00B8}'),
    Some('\u{00C6}'),
    Some('\u{00A4}'),
    // 0xA0-0xAF: More lowercase letters and symbols
    Some('\u{00B5}'),
    Some('~'),
    Some('s'),
    Some('t'),
    Some('u'),
    Some('v'),
    Some('w'),
    Some('x'),
    Some('y'),
    Some('z'),
    Some('\u{00A1}'),
    Some('\u{00BF}'),
    Some('\u{00D0}'),
    Some('\u{00DD}'),
    Some('\u{00DE}'),
    Some('\u{00AE}'),
    // 0xB0-0xBF: Special characters
    Some('^'),
    Some('\u{00A3}'),
    Some('\u{00A5}'),
    Some('\u{00B7}'),
    Some('\u{00A9}'),
    Some('\u{00A7}'),
    Some('\u{00B6}'),
    Some('\u{00BC}'),
    Some('\u{00BD}'),
    Some('\u{00BE}'),
    Some('['),
    Some(']'),
    Some('\u{00AF}'),
    Some('\u{00A8}'),
    Some('\u{00B4}'),
    Some('\u{00D7}'),
    // 0xC0-0xCF: Special characters and uppercase letters
    Some('{'),
    Some('A'),
    Some('B'),
    Some('C'),
    Some('D'),
    Some('E'),
    Some('F'),
    Some('G'),
    Some('H'),
    Some('I'),
    Some('\u{00AD}'),
    Some('\u{00F4}'),
    Some('\u{00F6}'),
    Some('\u{00F2}'),
    Some('\u{00F3}'),
    Some('\u{00F5}'),
    // 0xD0-0xDF: More uppercase letters
    Some('}'),
    Some('J'),
    Some('K'),
    Some('L'),
    Some('M'),
    Some('N'),
    Some('O'),
    Some('P'),
    Some('Q'),
    Some('R'),
    Some('\u{00B9}'),
    Some('\u{00FB}'),
    Some('\u{00FC}'),
    Some('\u{00F9}'),
    Some('\u{00FA}'),
    Some('\u{00FF}'),
    // 0xE0-0xEF: More special characters and uppercase letters
    Some('\\'),
    Some('\u{00F7}'),
    Some('S'),
    Some('T'),
    Some('U'),
    Some('V'),
    Some('W'),
    Some('X'),
    Some('Y'),
    Some('Z'),
    Some('\u{00B2}'),
    Some('\u{00D4}'),
    Some('\u{00D6}'),
    Some('\u{00D2}'),
    Some('\u{00D3}'),
    Some('\u{00D5}'),
    // 0xF0-0xFF: Digits and final characters
    Some('0'),
    Some('1'),
    Some('2'),
    Some('3'),
    Some('4'),
    Some('5'),
    Some('6'),
    Some('7'),
    Some('8'),
    Some('9'),
    Some('\u{00B3}'),
    Some('\u{00DB}'),
    Some('\u{00DC}'),
    Some('\u{00D9}'),
    Some('\u{00DA}'),
    Some('\u{009F}'),
];

/// IBM EBCDIC Code Page 500 (International) - Similar to 037 but with some differences
pub static EBCDIC_500_CHARS: [Option<char>; 256] = EBCDIC_037_CHARS; // Simplified for now

/// IBM EBCDIC Code Page 1047 (Latin-1) - Used for open systems
pub static EBCDIC_1047_CHARS: [Option<char>; 256] = EBCDIC_037_CHARS; // Simplified for now

/// ISO-8859-15 (Latin-9) - Western European with Euro symbol
pub static ISO_8859_15_CHARS: [Option<char>; 256] = {
    let mut chars = ISO_8859_1_CHARS;
    // ISO-8859-15 changes from ISO-8859-1: Euro at 0xA4, other symbols
    chars[0xA4] = Some('\u{20AC}'); // Euro symbol
    chars[0xA6] = Some('\u{0160}'); // S caron
    chars[0xA8] = Some('\u{0161}'); // s caron
    chars[0xB4] = Some('\u{017D}'); // Z caron
    chars[0xB8] = Some('\u{017E}'); // z caron
    chars[0xBC] = Some('\u{0152}'); // OE ligature
    chars[0xBD] = Some('\u{0153}'); // oe ligature
    chars[0xBE] = Some('\u{0178}'); // Y diaeresis
    chars
};

/// Windows-1250 (Central/Eastern European)
pub static WINDOWS_1250_CHARS: [Option<char>; 256] = [
    // 0x00-0x7F: Same as ASCII
    Some('\u{0000}'),
    Some('\u{0001}'),
    Some('\u{0002}'),
    Some('\u{0003}'),
    Some('\u{0004}'),
    Some('\u{0005}'),
    Some('\u{0006}'),
    Some('\u{0007}'),
    Some('\u{0008}'),
    Some('\u{0009}'),
    Some('\u{000A}'),
    Some('\u{000B}'),
    Some('\u{000C}'),
    Some('\u{000D}'),
    Some('\u{000E}'),
    Some('\u{000F}'),
    Some('\u{0010}'),
    Some('\u{0011}'),
    Some('\u{0012}'),
    Some('\u{0013}'),
    Some('\u{0014}'),
    Some('\u{0015}'),
    Some('\u{0016}'),
    Some('\u{0017}'),
    Some('\u{0018}'),
    Some('\u{0019}'),
    Some('\u{001A}'),
    Some('\u{001B}'),
    Some('\u{001C}'),
    Some('\u{001D}'),
    Some('\u{001E}'),
    Some('\u{001F}'),
    Some(' '),
    Some('!'),
    Some('"'),
    Some('#'),
    Some('$'),
    Some('%'),
    Some('&'),
    Some('\''),
    Some('('),
    Some(')'),
    Some('*'),
    Some('+'),
    Some(','),
    Some('-'),
    Some('.'),
    Some('/'),
    Some('0'),
    Some('1'),
    Some('2'),
    Some('3'),
    Some('4'),
    Some('5'),
    Some('6'),
    Some('7'),
    Some('8'),
    Some('9'),
    Some(':'),
    Some(';'),
    Some('<'),
    Some('='),
    Some('>'),
    Some('?'),
    Some('@'),
    Some('A'),
    Some('B'),
    Some('C'),
    Some('D'),
    Some('E'),
    Some('F'),
    Some('G'),
    Some('H'),
    Some('I'),
    Some('J'),
    Some('K'),
    Some('L'),
    Some('M'),
    Some('N'),
    Some('O'),
    Some('P'),
    Some('Q'),
    Some('R'),
    Some('S'),
    Some('T'),
    Some('U'),
    Some('V'),
    Some('W'),
    Some('X'),
    Some('Y'),
    Some('Z'),
    Some('['),
    Some('\\'),
    Some(']'),
    Some('^'),
    Some('_'),
    Some('`'),
    Some('a'),
    Some('b'),
    Some('c'),
    Some('d'),
    Some('e'),
    Some('f'),
    Some('g'),
    Some('h'),
    Some('i'),
    Some('j'),
    Some('k'),
    Some('l'),
    Some('m'),
    Some('n'),
    Some('o'),
    Some('p'),
    Some('q'),
    Some('r'),
    Some('s'),
    Some('t'),
    Some('u'),
    Some('v'),
    Some('w'),
    Some('x'),
    Some('y'),
    Some('z'),
    Some('{'),
    Some('|'),
    Some('}'),
    Some('~'),
    Some('\u{007F}'),
    // 0x80-0x9F: Windows-1250 specific mappings
    Some('\u{20AC}'),
    None,
    Some('\u{201A}'),
    None,
    Some('\u{201E}'),
    Some('\u{2026}'),
    Some('\u{2020}'),
    Some('\u{2021}'),
    None,
    Some('\u{2030}'),
    Some('\u{0160}'),
    Some('\u{2039}'),
    Some('\u{015A}'),
    Some('\u{0164}'),
    Some('\u{017D}'),
    Some('\u{0179}'),
    None,
    Some('\u{2018}'),
    Some('\u{2019}'),
    Some('\u{201C}'),
    Some('\u{201D}'),
    Some('\u{2022}'),
    Some('\u{2013}'),
    Some('\u{2014}'),
    None,
    Some('\u{2122}'),
    Some('\u{0161}'),
    Some('\u{203A}'),
    Some('\u{015B}'),
    Some('\u{0165}'),
    Some('\u{017E}'),
    Some('\u{017A}'),
    // 0xA0-0xFF: Extended Latin characters for Central European languages
    Some('\u{00A0}'),
    Some('\u{02C7}'),
    Some('\u{02D8}'),
    Some('\u{0141}'),
    Some('\u{00A4}'),
    Some('\u{0104}'),
    Some('\u{00A6}'),
    Some('\u{00A7}'),
    Some('\u{00A8}'),
    Some('\u{00A9}'),
    Some('\u{015E}'),
    Some('\u{00AB}'),
    Some('\u{00AC}'),
    Some('\u{00AD}'),
    Some('\u{00AE}'),
    Some('\u{017B}'),
    Some('\u{00B0}'),
    Some('\u{00B1}'),
    Some('\u{02DB}'),
    Some('\u{0142}'),
    Some('\u{00B4}'),
    Some('\u{00B5}'),
    Some('\u{00B6}'),
    Some('\u{00B7}'),
    Some('\u{00B8}'),
    Some('\u{0105}'),
    Some('\u{015F}'),
    Some('\u{00BB}'),
    Some('\u{013D}'),
    Some('\u{02DD}'),
    Some('\u{013E}'),
    Some('\u{017C}'),
    Some('\u{0154}'),
    Some('\u{00C1}'),
    Some('\u{00C2}'),
    Some('\u{0102}'),
    Some('\u{00C4}'),
    Some('\u{0139}'),
    Some('\u{0106}'),
    Some('\u{00C7}'),
    Some('\u{010C}'),
    Some('\u{00C9}'),
    Some('\u{0118}'),
    Some('\u{00CB}'),
    Some('\u{011A}'),
    Some('\u{00CD}'),
    Some('\u{00CE}'),
    Some('\u{010E}'),
    Some('\u{0110}'),
    Some('\u{0143}'),
    Some('\u{0147}'),
    Some('\u{00D3}'),
    Some('\u{00D4}'),
    Some('\u{0150}'),
    Some('\u{00D6}'),
    Some('\u{00D7}'),
    Some('\u{0158}'),
    Some('\u{016E}'),
    Some('\u{00DA}'),
    Some('\u{0170}'),
    Some('\u{00DC}'),
    Some('\u{00DD}'),
    Some('\u{0162}'),
    Some('\u{00DF}'),
    Some('\u{0155}'),
    Some('\u{00E1}'),
    Some('\u{00E2}'),
    Some('\u{0103}'),
    Some('\u{00E4}'),
    Some('\u{013A}'),
    Some('\u{0107}'),
    Some('\u{00E7}'),
    Some('\u{010D}'),
    Some('\u{00E9}'),
    Some('\u{0119}'),
    Some('\u{00EB}'),
    Some('\u{011B}'),
    Some('\u{00ED}'),
    Some('\u{00EE}'),
    Some('\u{010F}'),
    Some('\u{0111}'),
    Some('\u{0144}'),
    Some('\u{0148}'),
    Some('\u{00F3}'),
    Some('\u{00F4}'),
    Some('\u{0151}'),
    Some('\u{00F6}'),
    Some('\u{00F7}'),
    Some('\u{0159}'),
    Some('\u{016F}'),
    Some('\u{00FA}'),
    Some('\u{0171}'),
    Some('\u{00FC}'),
    Some('\u{00FD}'),
    Some('\u{0163}'),
    Some('\u{02D9}'),
];

/// DOS Code Page 437 (US OEM) - The original PC character set
pub static CP_437_CHARS: [Option<char>; 256] = [
    // 0x00-0x1F: Control characters
    Some('\u{0000}'),
    Some('\u{0001}'),
    Some('\u{0002}'),
    Some('\u{0003}'),
    Some('\u{0004}'),
    Some('\u{0005}'),
    Some('\u{0006}'),
    Some('\u{0007}'),
    Some('\u{0008}'),
    Some('\u{0009}'),
    Some('\u{000A}'),
    Some('\u{000B}'),
    Some('\u{000C}'),
    Some('\u{000D}'),
    Some('\u{000E}'),
    Some('\u{000F}'),
    Some('\u{0010}'),
    Some('\u{0011}'),
    Some('\u{0012}'),
    Some('\u{0013}'),
    Some('\u{0014}'),
    Some('\u{0015}'),
    Some('\u{0016}'),
    Some('\u{0017}'),
    Some('\u{0018}'),
    Some('\u{0019}'),
    Some('\u{001A}'),
    Some('\u{001B}'),
    Some('\u{001C}'),
    Some('\u{001D}'),
    Some('\u{001E}'),
    Some('\u{001F}'),
    // 0x20-0x7F: Standard ASCII
    Some(' '),
    Some('!'),
    Some('"'),
    Some('#'),
    Some('$'),
    Some('%'),
    Some('&'),
    Some('\''),
    Some('('),
    Some(')'),
    Some('*'),
    Some('+'),
    Some(','),
    Some('-'),
    Some('.'),
    Some('/'),
    Some('0'),
    Some('1'),
    Some('2'),
    Some('3'),
    Some('4'),
    Some('5'),
    Some('6'),
    Some('7'),
    Some('8'),
    Some('9'),
    Some(':'),
    Some(';'),
    Some('<'),
    Some('='),
    Some('>'),
    Some('?'),
    Some('@'),
    Some('A'),
    Some('B'),
    Some('C'),
    Some('D'),
    Some('E'),
    Some('F'),
    Some('G'),
    Some('H'),
    Some('I'),
    Some('J'),
    Some('K'),
    Some('L'),
    Some('M'),
    Some('N'),
    Some('O'),
    Some('P'),
    Some('Q'),
    Some('R'),
    Some('S'),
    Some('T'),
    Some('U'),
    Some('V'),
    Some('W'),
    Some('X'),
    Some('Y'),
    Some('Z'),
    Some('['),
    Some('\\'),
    Some(']'),
    Some('^'),
    Some('_'),
    Some('`'),
    Some('a'),
    Some('b'),
    Some('c'),
    Some('d'),
    Some('e'),
    Some('f'),
    Some('g'),
    Some('h'),
    Some('i'),
    Some('j'),
    Some('k'),
    Some('l'),
    Some('m'),
    Some('n'),
    Some('o'),
    Some('p'),
    Some('q'),
    Some('r'),
    Some('s'),
    Some('t'),
    Some('u'),
    Some('v'),
    Some('w'),
    Some('x'),
    Some('y'),
    Some('z'),
    Some('{'),
    Some('|'),
    Some('}'),
    Some('~'),
    Some('\u{007F}'),
    // 0x80-0xFF: CP437 extended characters (box drawing, accented chars, etc.)
    Some('\u{00C7}'),
    Some('\u{00FC}'),
    Some('\u{00E9}'),
    Some('\u{00E2}'),
    Some('\u{00E4}'),
    Some('\u{00E0}'),
    Some('\u{00E5}'),
    Some('\u{00E7}'),
    Some('\u{00EA}'),
    Some('\u{00EB}'),
    Some('\u{00E8}'),
    Some('\u{00EF}'),
    Some('\u{00EE}'),
    Some('\u{00EC}'),
    Some('\u{00C4}'),
    Some('\u{00C5}'),
    Some('\u{00C9}'),
    Some('\u{00E6}'),
    Some('\u{00C6}'),
    Some('\u{00F4}'),
    Some('\u{00F6}'),
    Some('\u{00F2}'),
    Some('\u{00FB}'),
    Some('\u{00F9}'),
    Some('\u{00FF}'),
    Some('\u{00D6}'),
    Some('\u{00DC}'),
    Some('\u{00A2}'),
    Some('\u{00A3}'),
    Some('\u{00A5}'),
    Some('\u{20A7}'),
    Some('\u{0192}'),
    Some('\u{00E1}'),
    Some('\u{00ED}'),
    Some('\u{00F3}'),
    Some('\u{00FA}'),
    Some('\u{00F1}'),
    Some('\u{00D1}'),
    Some('\u{00AA}'),
    Some('\u{00BA}'),
    Some('\u{00BF}'),
    Some('\u{2310}'),
    Some('\u{00AC}'),
    Some('\u{00BD}'),
    Some('\u{00BC}'),
    Some('\u{00A1}'),
    Some('\u{00AB}'),
    Some('\u{00BB}'),
    Some('\u{2591}'),
    Some('\u{2592}'),
    Some('\u{2593}'),
    Some('\u{2502}'),
    Some('\u{2524}'),
    Some('\u{2561}'),
    Some('\u{2562}'),
    Some('\u{2556}'),
    Some('\u{2555}'),
    Some('\u{2563}'),
    Some('\u{2551}'),
    Some('\u{2557}'),
    Some('\u{255D}'),
    Some('\u{255C}'),
    Some('\u{255B}'),
    Some('\u{2510}'),
    Some('\u{2514}'),
    Some('\u{2534}'),
    Some('\u{252C}'),
    Some('\u{251C}'),
    Some('\u{2500}'),
    Some('\u{253C}'),
    Some('\u{255E}'),
    Some('\u{255F}'),
    Some('\u{255A}'),
    Some('\u{2554}'),
    Some('\u{2569}'),
    Some('\u{2566}'),
    Some('\u{2560}'),
    Some('\u{2550}'),
    Some('\u{256C}'),
    Some('\u{2567}'),
    Some('\u{2568}'),
    Some('\u{2564}'),
    Some('\u{2565}'),
    Some('\u{2559}'),
    Some('\u{2558}'),
    Some('\u{2552}'),
    Some('\u{2553}'),
    Some('\u{256B}'),
    Some('\u{256A}'),
    Some('\u{2518}'),
    Some('\u{250C}'),
    Some('\u{2588}'),
    Some('\u{2584}'),
    Some('\u{258C}'),
    Some('\u{2590}'),
    Some('\u{2580}'),
    Some('\u{03B1}'),
    Some('\u{00DF}'),
    Some('\u{0393}'),
    Some('\u{03C0}'),
    Some('\u{03A3}'),
    Some('\u{03C3}'),
    Some('\u{00B5}'),
    Some('\u{03C4}'),
    Some('\u{03A6}'),
    Some('\u{0398}'),
    Some('\u{03A9}'),
    Some('\u{03B4}'),
    Some('\u{221E}'),
    Some('\u{03C6}'),
    Some('\u{03B5}'),
    Some('\u{2229}'),
    Some('\u{2261}'),
    Some('\u{00B1}'),
    Some('\u{2265}'),
    Some('\u{2264}'),
    Some('\u{2320}'),
    Some('\u{2321}'),
    Some('\u{00F7}'),
    Some('\u{2248}'),
    Some('\u{00B0}'),
    Some('\u{2219}'),
    Some('\u{00B7}'),
    Some('\u{221A}'),
    Some('\u{207F}'),
    Some('\u{00B2}'),
    Some('\u{25A0}'),
    Some('\u{00A0}'),
];

/// DOS Code Page 850 (Western European OEM)
pub static CP_850_CHARS: [Option<char>; 256] = CP_437_CHARS; // Simplified - uses CP437 as base
